export const state = {
  allPosts:[],
  relatedPosts:[],
  slider1:0,
  slider2:0,
  slider3:0,
  slider4:0,
  posts:[],
  blogEditors:[],
  fontSize:"",
  templateToUse: { type: "", template: "" },
  section: "myResume",
  templates: [],
  resumes: [],
  templateToBeDownload: [],

  searchResult: "",
  user: {
    editor:false,
    viewersDataIdentifier:{},
    contentEdit:false,
    userCurrentData:{},
    languages:[],
    userTotalTemplates:[],
    trynow: "",
    isGonGon: false,
    accesstoken: "",
    initials: "",
    myTemplates: [],
    myResumes: [],
    siteUserName: "",
    images: {},
    inputData: [],
    coverLetter: {},
    persData: "",
    socLinks: "",
    educations: [],
    certifications: [],
    experiences: [],
    skills: [],
    jobDuty:[],
    jobDutyAdded:false,
    hobies: [],
    reffrences: [],
    template: "",
    file: "",
    token: "",
    email: "",
    password: "",
    userid: "",
  },
  allData: "",
  page: 1,
  resume: {},
  cloud_image: {},
};
