export const state = {
  content1:[],
  content2:[],
  content3:[],
  fontSize:"",
  templateToUse: { type: "", template: "" },
  section: "myResume",
  templates: [],
  resumes: [],
  templateToBeDownload: [],

  searchResult: "",
  user: {
    userTotalTemplates:[],
    trynow: "",
    isGonGon: false,
    accesstoken: "",
    initials: "",
    myTemplates: [],
    myResumes: [],
    siteUserName: "",
    images: {},
    inputData: [],
    coverLetter: {},
    persData1: "",
    persData2: "",
    socLinks: "",
    eduData: [],
    expeData: [],
    summeryData: [],
    educations: [],
    certifications: [],
    experiences: [],
    skills: [],
    hobies: [],
    reffrences: [],
    template: "",
    file: "",
    token: "",
    email: "",
    password: "",
    userid: "",
  },
  allData: "",
  page: 1,
  resume: {},
  cloud_image: {},
};
